# If I don't specify the alpine version here, 
# does it default to latest lts?
FROM python:alpine 

# RUN apk add --no-cache --virtual .gyp \
#         python \
#         make \
#         g++ \
#     && npm install \
#     && apk del .gyp